trigger: none

pr:
  branches:
    include:
      - 'next'

variables:
  - group: choreo-apim-analytics

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: build_and_unit_test
    displayName: Build And Unit Test
    timeoutInMinutes: 60
    steps:
      - template: templates/install-nodejs.yaml
      - template: templates/build-unit-tests.yml
