language: java
sudo: false

# Using -q Quiet output which only show errors, to overcome TravisCI log limit issue
script: travis_wait 100 mvn clean install -q -B -V

cache:
  directories:
  - $HOME/.m2
