# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Shop Around You API
  description: This API allows you to find shops near you and get price estimation for products you need.
  version: "1.0.0"
# the domain of the service
host: localhost
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /block:
    get:
      summary: throttled events available
      description: |
        This will provide access to throttled events in database.
      responses:
        200:
          description: An array of shops around you
          schema:
            type: object
            additionalProperties:
              $ref: "#/definitions/BlockConditions"

definitions:
  BlockConditions:
    properties:
              api:
                type: array
                items:
                 type: string
              application:
                type: array
                items:
                 type: string
              ip:
                type: array
                items:
                 type: string
